export const interiorFeatures = [
    ['ADSL', 'adsl'],
    ['Alarm', 'alarm'],
    ['Balcony', 'balcony'],
    ['Build-in Kitchen', 'buildinKitchen'],
    ['Barbecue', 'barbecue'],
    ['Funished', 'funished'],
    ['Air Conditioning', 'airConditioning'],
    ['Wallpaper', 'wallpaper'],
    ['Laundry Room', 'laundryRoom'],
    ['Dressing Room', 'dressingRoom'],
    ['Video Intercom', 'videoIntercom'],
    ['Jacuzzi', 'jacuzzi'],
    ['Shower', 'shower'],
    ['TV Satellite', 'tvSatellite'],
    ['Laminate', 'laminate'],
    ['Panel Door', 'panelDoor'],
    ['Mable Floor', 'mableFloor'],
    ['Blinds', 'blinds'],
    ['Sauna', 'sauna'],
    ['Parent Bathroom', 'parentBathroom'],
    ['Parquet', 'parquet'],
    ['Satin Plaster', 'satinPlaster'],
    ['Satin Color', 'satinColor'],
    ['Ceramic Floor', 'ceramicFloor'],
    ['Spotlight', 'spotlight'],
    ['Fireplace', 'fireplace'],
    ['Terrace', 'terrace'],
    ['Cloakroom', 'cloakroom'],
    ['Underfloor Heating', 'underfloorHeating'],
    ['Double Glazing', 'doubleGlazing'],
]

export const externalFeatures = [
    ['Elevator', 'elevator'],
    ['Gardened', 'gardened'],
    ['Fitness', 'fitness'],
    ['Security', 'security'],
    ['Thermal Insulation', 'thermalInsulation'],
    ['Generator', 'generator'],
    ['Doorman', 'doorman'],
    ['Car Park', 'carPark'],
    ['Playground', 'playground'],
    ['PVC', 'pvc'],
    ['Siding', 'siding'],
    ['Water Tank', 'waterTank'],
    ['Tennis Court', 'tennisCourt'],
    ['Fire Escape', 'fireEscape'],
    ['Swimming Pool', 'swimmingPool'],
    ['Football Field', 'footballField'],
    ['Basketball Field', 'basketballField'],
    ['Market', 'market'],
]